SELECT P.RAZAOSOCIAL AS RAZAO,
  D.NODOCUMENTO,
  D.COMPLDOCUMENTO,
  L.VALOR,
  L.VLRLIQUIDO,
  D.CODDOCUMENTO,
  MD.NOMEMODULO,
  D.PLACONTA,
  D.CODSUBCONTA,
  D.UNIDNEGOC,
  D.CODCENTROCUSTO,
  L.DATALANCTO,
  D.DATAEMISSAO,
  D.NOSSONUMERO,
  L.HISTORICOCOMPL,
  D.DATAPROGRAMADA,
  D.DATAVENCTO,
  L.PLNCODIGO,
  U.NOMEUSUARIO,
  P.NOME AS NOMERAZAO,
  T.DESCRICAO AS TIPODEB_CRED
FROM PESSOA P,
  DOCUMENTO D,
  LANCTODOCUM L,
  MODULO MD,
  USUARIOSISTEMA U,
  TIPODOCRECPAG T
WHERE (D.IDFORCLI        = P.IDPESSOA)
AND (D.IDMODULO          = MD.IDMODULO)
AND (D.OPERACAO          = L.OPERACAO)
AND (D.CODDOCUMENTO      = L.CODDOCUMENTO)
AND (D.IDUSUARIOINCLUSAO = U.IDUSUARIO(+))
AND (D.CODTIPDOC         = T.CODTIPDOC)
AND ((D.IDFORCLI         > 0
AND D.OPERACAO           = '1'
AND D.IDPESSOA           = 1
AND D.STATUS             = '0'
AND D.RECPAG             = 'R'
AND L.DATALANCTO        >= to_date('01/01/2000', 'dd/mm/yyyy'))
AND L.ESTORNO           IS NULL)
ORDER BY 1,
  12,
  17



