--No campo 'USU.NOMEUSUARIO' colocar o usuário CM do gerente em questão
SELECT
    GR.NOME,
    USU.NOMEUSUARIO,
    USUS.NOMEUSUARIO AS NOMEUSUARIOSUBS
FROM
    RADRESPONXGRP RXP,
    USUARIOSISTEMA USU,
    USUARIOSISTEMA USUS,
    RADGRPRESPON GR
WHERE
    USU.NOMEUSUARIO = 'EDSON.GONCALVES' and
    ( RXP.IDUSUARIO     = USU.IDUSUARIO )    AND
    ( RXP.IDUSUARIOSUBS = USUS.IDUSUARIO(+) )    AND
    ( RXP.FLGUSRSUBST is null ) AND
      rxp.IDGRPRESPON=GR.IDGRPRESPON
ORDER BY
    GR.NOME


