 SELECT
  C.IDCONSUMOSPDV, C.NUMMESA, C.IDHOTEL, C.IDTIPODEBCRED,
  T.DESCRICAO, L.IDTURNO, PT.DESCTURNO, C.STATUSCONSUMOSPDV,
  (SUM(L.QUANTIDADE * (L.PRECOUNITARIO - NVL(L.VALORDESCONTOITEM,0)))) AS VALORTOTAL
FROM
  CONSUMOSPDV C, TIPODEBCREDHOTEL T, LANCAMENTOSPDV L, PDVTURNO PT
WHERE
  (C.IDHOTEL = T.IDHOTEL) AND
  (C.IDTIPODEBCRED = T.IDTIPODEBCRED) AND
  (C.IDCONSUMOSPDV = L.IDCONSUMOSPDV(+)) AND
  (L.IDTURNO = PT.IDTURNO(+)) AND
  (C.STATUSCONSUMOSPDV IN ('I','O', 'P')) AND
  (C.DATAFISCAL = to_date('16/07/2015','dd/mm/yyyy')) AND
  (C.IDHOTEL = 20)
GROUP BY
  C.IDCONSUMOSPDV, C.NUMMESA, C.IDHOTEL, C.IDTIPODEBCRED, T.DESCRICAO, L.IDTURNO,
  PT.DESCTURNO, C.STATUSCONSUMOSPDV

  SELECT * FROM consumospdv c WHERE c.statusconsumospdv = 'I' AND C.DATAFISCAL = to_date('16/07/2015','dd/mm/yyyy') AND
  (C.IDHOTEL = 20) ;

  UPDATE consumospdv c SET c.statusconsumospdv = 'I' WHERE C.DATAFISCAL = to_date('16/07/2015','dd/mm/yyyy') AND
  (C.IDHOTEL = 20) ;


SELECT * FROM park2.lancamentoproduto WHERE numero = 36094657;

SELECT * FROM pdv.produto WHERE id = 200111;

SELECT * FROM pdv.produto WHERE id = 744;

SELECT * FROM pdv.pdv WHERE id = 55;

SELECT idtipodebcred,descricao FROM tipodebcredhotel WHERE descricao LIKE '%PIZZARIA%';