SELECT DISTINCT
CASE 
        --WHEN FUNCIONARIO.CODCOLIGADA = '1' THEN '00.866.577/0017-48'
        --WHEN FUNCIONARIO.CODCOLIGADA = '2' THEN '00.866.577/0018-29'
		WHEN FUNCIONARIO.CODCOLIGADA = '3' THEN '00.866.577/0001-80'
		--WHEN FUNCIONARIO.CODCOLIGADA = '4' THEN '03.720.753/0001-60'
        END AS Empresa_CNPJ,
	  CASE 	
	    --WHEN FUNCIONARIO.CODCOLIGADA = '1' THEN 'COSTA DO SAUIPE GOLF & SPA'
        --WHEN FUNCIONARIO.CODCOLIGADA = '2' THEN 'COSTA DO SAUIPE ALL INCLUSIVE'
		WHEN FUNCIONARIO.CODCOLIGADA = '3' THEN 'SAUIPE S.A'
		--WHEN FUNCIONARIO.CODCOLIGADA = '4' THEN 'CONDOMINIO COSTA DO SAUIPE'
      END AS Setor,
	  FUNCAO.CODIGO AS CODFUNCAO,
      CASE 
           WHEN FUNCAO.NOME IS NULL THEN 'Nao Informado'
           ELSE FUNCAO.NOME 
	   END AS Cargo,
	   --NULL AS Descricao_Atividades,
       --NULL AS Informacoes_Complementares,
	   FUNCIONARIO.CHAPA AS Matricula,
	   PESSOA.NOME AS Nome,
       CONVERT(varchar, PESSOA.DTNASCIMENTO, 103) AS Data_Nascimento,
	   CASE 
            WHEN PESSOA.SEXO = 'M' THEN 'M'
            WHEN PESSOA.SEXO = 'F' THEN 'F'
        END AS Sexo,
	   CONVERT(varchar, FUNCIONARIO.DATAADMISSAO, 103) AS Data_Admissao,
	   /*CASE 
            WHEN PESSOA.ESTADOCIVIL = 'C' THEN 'Casado(a)'
            WHEN PESSOA.ESTADOCIVIL = 'D' THEN 'Desquitado(a)'
            WHEN PESSOA.ESTADOCIVIL = 'E' THEN 'MARITAL - DECLARACAO DE UNIAO ESTÁVEL'
            WHEN PESSOA.ESTADOCIVIL = 'S' THEN 'Solteiro(a)' 
            WHEN PESSOA.ESTADOCIVIL = 'V' THEN 'Viúvo(a)'
			WHEN PESSOA.ESTADOCIVIL = 'M' THEN 'MARITAL - DECLARACAO DE UNIAO ESTÁVEL'
			WHEN PESSOA.ESTADOCIVIL = 'P' THEN 'Separado(a)'
			WHEN PESSOA.ESTADOCIVIL = 'I' THEN 'Divorciado(a)'
        END AS Estado_Civil, */
		--FUNCIONARIO.PISPASEP AS NIT_PIS_PASEP,
		--PESSOA.CARTIDENTIDADE AS RG,   
		SUBSTRING(PESSOA.CPF,1,3) + '.' +  SUBSTRING(PESSOA.CPF,4,3) + '.' +  SUBSTRING(PESSOA.CPF,7,3) + '-' +  SUBSTRING(PESSOA.CPF,10,2) AS CPF,
		--PESSOA.CARTEIRATRAB AS CTPS,
		--replace( (right (replicate('0',2) + convert(VARCHAR,PESSOA.SERIECARTTRAB),3) ), '-','')  AS SERIE,
		--NULL AS CNS,
		CASE 
            WHEN FUNCIONARIO.TIPOADMISSAO = 'E' THEN 'TRANSFERIDO' --Entrada Transf. c/ onus p/ Cedente
            WHEN FUNCIONARIO.TIPOADMISSAO = 'I' THEN 'CLT' --Reintegração
            WHEN FUNCIONARIO.TIPOADMISSAO = 'O' THEN 'Outro' --Outros Casos
            WHEN FUNCIONARIO.TIPOADMISSAO = 'P' THEN 'CLT' --Primeiro Emprego
            WHEN FUNCIONARIO.TIPOADMISSAO = 'R' THEN 'CLT' --Reemprego
            WHEN FUNCIONARIO.TIPOADMISSAO = 'T' THEN 'TRANSFERIDO' --Entrada Transf. s/ onus p/ Cedente
        END AS Vinculo,  
		--NULL AS Vinculo_Outro,
		SESSAO.COD AS cod_cc,
	    SESSAO.DESCRICAO AS Centro_Custo,        
        CASE 
            WHEN FUNCIONARIO.CODSITUACAO = 'A' THEN 'Ativo'
            WHEN FUNCIONARIO.CODSITUACAO = 'D' THEN 'Demitidos'
            WHEN FUNCIONARIO.CODSITUACAO = 'E' THEN 'Licenca Maternidade'
            WHEN FUNCIONARIO.CODSITUACAO = 'F' THEN 'Férias'
            WHEN FUNCIONARIO.CODSITUACAO = 'I' THEN 'Aposentados por Invalidez'
			WHEN FUNCIONARIO.CODSITUACAO = 'O' THEN 'Afastado B91'
			WHEN FUNCIONARIO.CODSITUACAO = 'P' THEN 'Afastado'
			WHEN FUNCIONARIO.CODSITUACAO = 'T' THEN 'Afastado B91'
			WHEN FUNCIONARIO.CODSITUACAO = 'U' THEN 'Autonomo' --Ver se há registros (caso SIM retirar da carga)
			WHEN FUNCIONARIO.CODSITUACAO = 'Z' THEN 'Ativo'
			WHEN FUNCIONARIO.CODSITUACAO = 'C' THEN 'Suspensao Contrato de Trabalho'
			WHEN FUNCIONARIO.CODSITUACAO = 'G' THEN 'Recesso'
			WHEN FUNCIONARIO.CODSITUACAO = 'V' THEN 'Ativo'
			WHEN FUNCIONARIO.CODSITUACAO = 'M' THEN 'Servico Militar'
        END AS Situacao,      
		CASE
            WHEN FUNCIONARIO.CODSITUACAO =  'A' THEN NULL
			WHEN FUNCIONARIO.CODSITUACAO='D' THEN NULL
			WHEN FUNCIONARIO.CODSITUACAO =  'F' THEN CONVERT(varchar,FERIAS.DATAINICIO, 103)  
			WHEN 
			     AFASTAMENTO.TIPO =  'O' OR 
		         AFASTAMENTO.TIPO =  'P' OR 
				 AFASTAMENTO.TIPO =  'T' OR
				 AFASTAMENTO.TIPO =  'I' OR
				 AFASTAMENTO.TIPO =  'E'
		    THEN CONVERT(varchar, AFASTAMENTO.DTINICIO, 103) 
	    END AS Situacao_Data_Inicio,
	    CASE
            WHEN FUNCIONARIO.CODSITUACAO =  'A' THEN NULL 
			WHEN FUNCIONARIO.CODSITUACAO =  'F' THEN CONVERT(varchar,FERIAS.DATAFIM, 103) 
			--WHEN FUNCIONARIO.CODSITUACAO='P'THEN '01/01/9999'
			WHEN AFASTAMENTO.DTFINAL IS NULL AND FUNCIONARIO.CODSITUACAO<>'D' THEN '01/01/9999'
			--WHEN FUNCIONARIO.CODSITUACAO='D'THEN NULL
			WHEN 
			     AFASTAMENTO.TIPO =  'O' OR 
		         AFASTAMENTO.TIPO =  'P' OR 
				 AFASTAMENTO.TIPO =  'T' OR
				 AFASTAMENTO.TIPO =  'I' OR
				 AFASTAMENTO.TIPO =  'E'
		    THEN CONVERT(varchar, AFASTAMENTO.DTFINAL, 103) 
		END AS Situacao_Data_Fim
FROM PFUNC FUNCIONARIO LEFT JOIN PPESSOA PESSOA ON (FUNCIONARIO.CODPESSOA = PESSOA.CODIGO)
					   LEFT JOIN (SELECT CHAPA,MAX(DTINICIO) DTINICIO   FROM PFHSTAFT GROUP BY CHAPA) MA ON (FUNCIONARIO.CHAPA = MA.CHAPA)
			           LEFT JOIN PFHSTAFT AFASTAMENTO ON MA.CHAPA=AFASTAMENTO.CHAPA AND AFASTAMENTO.DTINICIO=MA.DTINICIO
			           left join PFUFERIASPER FERIAS ON FERIAS.CHAPA=FUNCIONARIO.CHAPA AND FERIAS.SITUACAOFERIAS='P'
                       INNER JOIN PFDEPEND PARENTE ON (PARENTE.CHAPA = FUNCIONARIO.CHAPA)
					   INNER JOIN PFUNCAO FUNCAO ON (FUNCAO.CODIGO = FUNCIONARIO.CODFUNCAO) AND FUNCIONARIO.CODCOLIGADA=FUNCAO.CODCOLIGADA
					   INNER JOIN PSECAO SESSAO ON (SESSAO.CODIGO = FUNCIONARIO.CODSECAO) AND FUNCIONARIO.CODCOLIGADA=SESSAO.CODCOLIGADA
AND PARENTE.CODCOLIGADA = FUNCIONARIO.CODCOLIGADA
AND FUNCIONARIO.CODCOLIGADA = '3'
AND PARENTE.GRAUPARENTESCO = '7'
--AND PESSOA.FUNCIONARIO = 1

WHERE (FUNCIONARIO.CODSITUACAO IN ('A', 'E', 'F', 'I', 'O', 'P', 'T', 'Z', 'C', 'G', 'V', 'M')) AND FUNCIONARIO.CODCOLIGADA = 3;