--Ver se o TCK foi baixado

  SELECT IDLANCAMENTO,IDHOTEL,IDCONTA,PLNCODIGO,IDUSUARIO,IDCONTAORIGEM,DOCUMENTO,
        VLRLANCAMENTO,DATALANCAMENTO,HORALANCAMENTO,IDNOTAFRONT FROM cm.lancamentosfront
    WHERE documento LIKE 'TCK: 364646%'

    SELECT locreserva FROM reservasfront WHERE numreserva = 151877416;

    SELECT * FROM pessoa WHERE idpessoa=27;

--Retorna a resrva em que o tck foi baixado, (passando o Localizador "LOCRESERVA").
SELECT
   RF.LOCRESERVA,
   RF.NUMRESERVA,
   RF.IDRESERVASFRONT,
   RF.IDHOTEL,
   RF.CODUH,
   RF.STATUSRESERVA,
   RF.DATACHEGPREVISTA,
   RF.DATAPARTPREVISTA,
   RF.DATACHEGADAREAL,
   RF.DATAPARTIDAREAL,
   RF.HORAPARTIDAREAL,
   RF.USUARIO,
   RF.IDUSUALTERACAO,
   CF.IDCONTA,
   CF.DESIGNACAO,
   LF.DOCUMENTO,
   LF.VLRLANCAMENTO,
   LF.DATALANCAMENTO,
   LF.TRGDTINCLUSAO,
   LF.IDNOTAFRONT,
   LF.IDUSUARIO
FROM
  CONTASFRONT CF
    JOIN RESERVASFRONT RF ON
      (CF.IDRESERVASFRONT = RF.IDRESERVASFRONT)
    JOIN LANCAMENTOSFRONT LF ON
      (CF.IDCONTA = LF.IDCONTA)
WHERE
  (LF.DOCUMENTO LIKE ('TCK:%')) AND
  (RF.LOCRESERVA IN ('772067'))

--Remover data hora baixafornecedor da reserva
$repository.consulta('reservations/83723').custom_data.remove 'DataHoraBaixaFornecedor'
