  CREATE OR REPLACE VIEW "AUTOSEG"."V_FUNCIONARIOS" ("FILIAL", "EMPRESA_CNPJ", "SETOR", "COD_CARGO", "IDCARGOPROTHEUS", "MATRICULA", "NOME", "DATA_ADMISSAO", "CPF", "VINCULO", "TELEFONE", "CELULAR", "EMAIL", "CENTRO_CUSTO", "SITUACAO", "SITUACAO_DATA_INICIO_AFAST", "SITUACAO_DATA_FIM_AFAST", "DATA_DEMISSAO") AS 
  SELECT 
		   F.RA_FILIAL AS FILIAL,
           CASE 
                WHEN F.RA_FILIAL = '0101' THEN '01.540.533/0001-29'
                WHEN F.RA_FILIAL = '0102' THEN '01.540.533/0007-14'
                WHEN F.RA_FILIAL = '0103' THEN '01.540.533/0002-00'
                WHEN F.RA_FILIAL = '0104' THEN '01.540.533/0013-62'
                WHEN F.RA_FILIAL = '0105' THEN '01.540.533/0012-81'
                WHEN F.RA_FILIAL = '0106' THEN '01.540.533/0003-90'
                WHEN F.RA_FILIAL = '0107' THEN '01.540.533/0016-05'
                WHEN F.RA_FILIAL = '0108' THEN '01.540.533/0006-33' 
                WHEN F.RA_FILIAL = '0109' THEN '01.540.533/0008-03' 
                WHEN F.RA_FILIAL = '0110' THEN '01.540.533/0009-86' 
                WHEN F.RA_FILIAL = '0111' THEN '01.540.533/0010-10'
                WHEN F.RA_FILIAL = '0112' THEN '01.540.533/0011-09' 
                WHEN F.RA_FILIAL = '0113' THEN '01.540.533/0014-43'
                WHEN F.RA_FILIAL = '0114' THEN '01.540.533/0015-24'
                WHEN F.RA_FILIAL = '0201' THEN '04.171.002/0001-02'
                WHEN F.RA_FILIAL = '0301' THEN '05.417.496/0001-17'
                WHEN F.RA_FILIAL = '0401' THEN '07.137.035/0001-16'
                WHEN F.RA_FILIAL = '0501' THEN '01.288.778/0001-00'
                WHEN F.RA_FILIAL = '0601' THEN '01.787.563/0001-34'
                WHEN F.RA_FILIAL = '0701' THEN '01.808.716/0001-82'
				WHEN F.RA_FILIAL = '0801' THEN '02.082.394/0001-08'
				WHEN F.RA_FILIAL = '0802' THEN '02.082.394/0001-08'
                WHEN F.RA_FILIAL = '0803' THEN '02.082.394/0007-95' 
                WHEN F.RA_FILIAL = '0804' THEN '02.082.394/0013-33' 
                WHEN F.RA_FILIAL = '0805' THEN '02.082.394/0014-14' 
                WHEN F.RA_FILIAL = '0806' THEN '02.082.394/0015-03'
                WHEN F.RA_FILIAL = '0807' THEN '02.082.394/0016-86' 
                WHEN F.RA_FILIAL = '0901' THEN '02.359.156/0001-99'
				WHEN F.RA_FILIAL = '1001' THEN '02.397.156/0001-83'
				WHEN F.RA_FILIAL = '1101' THEN '02.987.159/0001-56'
				WHEN F.RA_FILIAL = '1201' THEN '22.434.149/0001-11'
				WHEN F.RA_FILIAL = '1301' THEN '02.082.394/0001-08'
				WHEN F.RA_FILIAL = '1402' THEN '00.866.577/0021-24'
           END AS Empresa_CNPJ,           
           CASE 
                WHEN F.RA_FILIAL = '0101' THEN 'CTRQ'
                WHEN F.RA_FILIAL = '0102' THEN 'CIA THERMAS DO RIO QUENTE - CALDAS NOVAS'
                WHEN F.RA_FILIAL = '0103' THEN 'CIA THERMAS DO RIO QUENTE - GYN'
                WHEN F.RA_FILIAL = '0104' THEN 'CIA THERMAS DO RIO QUENTE - PATIO BRASIL'
                WHEN F.RA_FILIAL = '0105' THEN 'CIA THERMAS DO RIO QUENTE - STO ANDRE'
                WHEN F.RA_FILIAL = '0106' THEN 'CIA THERMAS DO RIO QUENTE - VALETUR MART'
                WHEN F.RA_FILIAL = '0107' THEN 'FILIAL - MARULHOS'
                WHEN F.RA_FILIAL = '0108' THEN 'POUSADA BRASILIA'
                WHEN F.RA_FILIAL = '0109' THEN 'CIA THERMAS DO RIO QUENTE - SAO CAETANO' 
                WHEN F.RA_FILIAL = '0110' THEN 'CIA THERMAS DO RIO QUENTE - VILA LEOPONDIN' 
                WHEN F.RA_FILIAL = '0111' THEN 'CIA THERMAS DO RIO QUENTE - IBIRAPUERA'
                WHEN F.RA_FILIAL = '0112' THEN 'CIA THERMAS DO RIO QUENTE - CAMPINAS' 
                WHEN F.RA_FILIAL = '0113' THEN 'CIA THERMAS DO RIO QUENTE'
                WHEN F.RA_FILIAL = '0114' THEN 'RIO QUENTE RESORTS - RIBEIRAO PRETO'
                WHEN F.RA_FILIAL = '0201' THEN 'RQSF I'
                WHEN F.RA_FILIAL = '0301' THEN 'RQSF II'
                WHEN F.RA_FILIAL = '0401' THEN 'GIARDINO SUITES'
                WHEN F.RA_FILIAL = '0501' THEN 'ESTANCIA THERMAS POUSADA DO RIO QUENTE'
                WHEN F.RA_FILIAL = '0601' THEN 'ESTANCIA THERMAS DO RIO QUENTE'
                WHEN F.RA_FILIAL = '0701' THEN 'RIO QUENTE EMPREENDIMENTOS E PARTICIPACOE'
				WHEN F.RA_FILIAL = '0801' THEN 'VALE DO RIO QUENTE AG DE VIAGENS E TURIS'
				WHEN F.RA_FILIAL = '0802' THEN 'VALETUR BRASILIA'
                WHEN F.RA_FILIAL = '0803' THEN 'VALE DO RIO QUENTE AG DE VIAGENS E TURIS' 
                WHEN F.RA_FILIAL = '0804' THEN 'VALETUR SAO CAETANO' 
                WHEN F.RA_FILIAL = '0805' THEN 'VALETUR CALDAS NOVAS' 
                WHEN F.RA_FILIAL = '0806' THEN 'VALE DO RIO QUENTE AG DE VIAGENS E TURIS'
                WHEN F.RA_FILIAL = '0807' THEN 'VALE DO RIO QUENTE AG DE VIAGENS E TURIS' 
                WHEN F.RA_FILIAL = '0901' THEN 'RIO QUENTE MINERACAO'
				WHEN F.RA_FILIAL = '1001' THEN 'RIO QUENTE EMPREENDIMENTOS IMOBILIARIOS'
				WHEN F.RA_FILIAL = '1101' THEN 'RIO QUENTE INCORPORACOES E VENDAS LTDA'
				WHEN F.RA_FILIAL = '1201' THEN 'VALE DO RIO QUENTE OPERADORA DE TURISMO'
				WHEN F.RA_FILIAL = '1301' THEN 'VALETUR MATRIZ'
				WHEN F.RA_FILIAL = '1402' THEN 'SAUIPE GOIAS'
            END AS Setor,    
        trim(CASE 
           WHEN C.Q3_CARGO IS NULL THEN 'Nao Informado'
           ELSE C.Q3_CARGO 
	    END) AS Cod_Cargo,
		to_number(regexp_replace(F.RA_CARGO,'[^0-9]', '')) as idCargoProtheus,
--		CASE 
--           WHEN C.Q3_DESCSUM IS NULL THEN 'Nao Informado'
--           ELSE C.Q3_DESCSUM 
--	    END AS Cargo,
      F.RA_MAT AS Matricula, 
      trim(F.RA_NOMECMP) AS Nome, 
      Substr(F.RA_ADMISSA,7,2)||'/'||Substr(F.RA_ADMISSA,5,2)||'/'||Substr(F.RA_ADMISSA,0,4) AS Data_Admissao,     
      REGEXP_REPLACE(LPAD(F.RA_CIC, 11),'([0-9]{3})([0-9]{3})([0-9]{3})','\1.\2.\3-') AS CPF,     
      trim(CASE 
            WHEN C.Q3_DESCSUM IN 'ESTAGIARIO' AND  F.RA_PIS = ' ' THEN 'ESTAGIARIO'
            WHEN C.Q3_DESCSUM IS NULL AND  F.RA_PIS = ' ' THEN 'ESTAGIARIO'
            WHEN F.RA_TIPOADM = '1A' THEN 'DIRETOR'
            WHEN F.RA_TIPOADM = '1B' THEN 'DIRETOR'
            WHEN F.RA_TIPOADM = '1C' THEN 'DIRETOR'
            WHEN F.RA_TIPOADM = '2A' THEN 'CLT'
            WHEN F.RA_TIPOADM = '2B' THEN 'CLT'
            WHEN F.RA_TIPOADM = '2C' THEN 'CLT'
            WHEN F.RA_TIPOADM = '3A' THEN 'CLT'
            WHEN F.RA_TIPOADM = '3B' THEN 'CLT'
            WHEN F.RA_TIPOADM = '3C' THEN 'CLT'
            WHEN F.RA_TIPOADM = '4B' THEN 'CLT'
            WHEN F.RA_TIPOADM = '51' THEN 'CLT'
            WHEN F.RA_TIPOADM = '52' THEN 'CLT'
            WHEN F.RA_TIPOADM = '53' THEN 'CLT'
            WHEN F.RA_TIPOADM = '54' THEN 'CLT'
            WHEN F.RA_TIPOADM = '55' THEN 'CLT'
            WHEN F.RA_TIPOADM = '56' THEN 'CLT'
            WHEN F.RA_TIPOADM = '9A' THEN 'CLT'
            WHEN F.RA_TIPOADM = '9B' THEN 'CLT'
            WHEN F.RA_TIPOADM = '9C' THEN 'CLT'            
      END) AS Vinculo,      
      trim(F.RA_TELEFON) AS Telefone,
      trim(F.RA_NUMCELU) AS Celular,
      trim(F.RA_EMAIL) AS Email,
      trim(CC.CTT_DESC01) AS Centro_Custo,    
      CASE 
            WHEN F.RA_SITFOLH = ' ' THEN 'Ativo'
            WHEN F.RA_SITFOLH = 'F' THEN 'Férias'
            WHEN F.RA_SITFOLH = 'T' THEN 'Transferido'
            WHEN F.RA_SITFOLH = 'D' THEN 'Demitido'
            WHEN F.RA_SITFOLH = 'A' THEN 'Afastado' 
      END AS Situacao,       
      CASE 
            WHEN F.RA_SITFOLH = ' ' THEN 'NULL'
            WHEN F.RA_SITFOLH = 'F' OR
                 F.RA_SITFOLH = 'T' OR
                 F.RA_SITFOLH = 'A' 
      THEN Substr(D.R8_DATAINI,7,2)||'/'||Substr(D.R8_DATAINI,5,2)||'/'||Substr(D.R8_DATAINI,0,4) 
      END AS Situacao_Data_Inicio_Afast,
      CASE 
            WHEN F.RA_SITFOLH = ' ' THEN 'NULL'
            WHEN F.RA_SITFOLH = 'F' OR
                 F.RA_SITFOLH = 'T' OR
                 F.RA_SITFOLH = 'A' 
      THEN Substr(D.R8_DATAFIM,7,2)||'/'||Substr(D.R8_DATAFIM,5,2)||'/'||Substr(D.R8_DATAFIM,0,4)
      END AS Situacao_Data_Fim_Afast,
      Substr(F.RA_DEMISSA,7,2)||'/'||Substr(F.RA_DEMISSA,5,2)||'/'||Substr(F.RA_DEMISSA,0,4) AS Data_Demissao
      
FROM SIGA.SRA010 F

      LEFT JOIN SIGA.CTT010 CC ON (F.RA_CC = CC.CTT_CUSTO  AND Substr(F.RA_FILIAL,0,2) = trim(CC.CTT_FILIAL))
      LEFT JOIN SIGA.SQ3010 C  ON (F.RA_CARGO = C.Q3_CARGO AND Substr(F.RA_FILIAL,0,2) = trim(C.Q3_FILIAL))
      LEFT JOIN (SELECT R8_MAT, MAX(R8_SEQ) AS SEQ FROM SIGA.SR8010 GROUP BY R8_MAT) S ON (F.RA_MAT = S.R8_MAT)
      LEFT JOIN SIGA.SR8010 D  ON (S.R8_MAT = D.R8_MAT) AND D.R8_SEQ = S.SEQ AND D.D_E_L_E_T_ = ' '      

WHERE
	F.D_E_L_E_T_ = ' '
	AND F.RA_SITFOLH IN (' ' ,'D','A','F','T')
	AND F.RA_MAT NOT LIKE 'T%'
	--AND F.RA_MAT NOT LIKE 'R%'
WITH READ ONLY;