  CREATE OR REPLACE VIEW "FAPONLINE"."V_FUNCIONARIOS" ("FILIAL", "EMPRESA_CNPJ", "SETOR", "CARGO", "DESCRICAO_ATIVIDADES", "INFORMACOES_COMPLEMENTARES", "MATRICULA", "NOME", "DATA_NASCIMENTO", "SEXO", "DATA_ADMISSAO", "ESTADO_CIVIL", "NIT_PIS_PASEP", "RG", "CPF", "CTPS", "SERIE", "CNS", "VINCULO", "VINCULO_OUTRO", "ENDERECO", "ENDERECO_NUMERO", "COMPLEMENTO", "CIDADE", "ESTADO", "BAIRRO", "CEP", "TELEFONE", "CELULAR", "EMAIL", "SALARIO", "JORNADA_TRABALHO", "CENTRO_CUSTO", "CODIGO_POLO", "NOME_POLO", "CNPJ_LOTACAO", "CODIGO_LOTACAO", "NOME_LOTACAO", "ENDERECO_LOTACAO", "ENDERECO_LOTACAO_NUMERO", "ENDERECO_LOTACAO_COMPLEMENTO", "LOTACAO_BAIRRO", "LOTACAO_CEP", "CIDADE_LOTACAO", "ESTADO_LOTACAO", "SITUACAO", "SITUACAO_OUTRO", "SITUACAO_DATA_INICIO", "SITUACAO_DATA_FIM", "NOME_MAE", "CONTATO_EMERGENCIA", "DEFICIENCIA", "DEFICIENCIA_CLASSIFICACAO", "ESTABILIDADE", "ESTABILIDADE_DATA_INICIO", "ESTABILIDADE_DATA_FIM", "RISCOS", "RISCO_OUTROS", "HIERARQUIA", "NACIONALIDADE", "NOME_DEPENDENTES", "GRAU_PARENTESCO_DEPENDENTES", "SEXO_DEPENDENTES", "DT_NASCIMENTO_DEPENDENTES", "PRESTADOR", "NEGOCIO", "DIRETORIA", "GERENCIA", "ASSITENCIAMEDICA", "ARREDONDAMENTO", "DEVOLUCAOPAGAMENTOMAIOR", "MESALIDADEASSISTENCIAMEDICA", "COPARTICIPACAO", "ASSISTENCIAODONTOLOGICA", "SEGUROVIDA", "FGTS", "VALORASSISTENCIAMEDICA", "IDESOCIAL", "CODIGOCBO", "EXCLUSAO") AS 
  SELECT
   	F.RA_FILIAL AS FILIAL,
	CASE
		WHEN F.RA_FILIAL = '0101' THEN '01.540.533/0001-29'
		WHEN F.RA_FILIAL = '0102' THEN '01.540.533/0007-14'
		WHEN F.RA_FILIAL = '0103' THEN '01.540.533/0002-00'
		WHEN F.RA_FILIAL = '0104' THEN '01.540.533/0013-62'
		WHEN F.RA_FILIAL = '0105' THEN '01.540.533/0012-81'
		WHEN F.RA_FILIAL = '0106' THEN '01.540.533/0003-90'
		WHEN F.RA_FILIAL = '0107' THEN '01.540.533/0016-05'
		WHEN F.RA_FILIAL = '0108' THEN '01.540.533/0006-33'
		WHEN F.RA_FILIAL = '0109' THEN '01.540.533/0008-03'
		WHEN F.RA_FILIAL = '0110' THEN '01.540.533/0009-86'
		WHEN F.RA_FILIAL = '0111' THEN '01.540.533/0010-10'
		WHEN F.RA_FILIAL = '0112' THEN '01.540.533/0011-09'
		WHEN F.RA_FILIAL = '0113' THEN '01.540.533/0014-43'
		WHEN F.RA_FILIAL = '0114' THEN '01.540.533/0015-24'
		WHEN F.RA_FILIAL = '0201' THEN '04.171.002/0001-02'
		WHEN F.RA_FILIAL = '0301' THEN '05.417.496/0001-17'
		WHEN F.RA_FILIAL = '0401' THEN '07.137.035/0001-16'
		WHEN F.RA_FILIAL = '0501' THEN '01.288.778/0001-00'
		WHEN F.RA_FILIAL = '0601' THEN '01.787.563/0001-34'
		WHEN F.RA_FILIAL = '0701' THEN '01.808.716/0001-82'
		WHEN F.RA_FILIAL = '0801' THEN '02.082.394/0001-08'
		WHEN F.RA_FILIAL = '0802' THEN '02.082.394/0001-08'
		WHEN F.RA_FILIAL = '0803' THEN '02.082.394/0007-95'
		WHEN F.RA_FILIAL = '0804' THEN '02.082.394/0013-33'
		WHEN F.RA_FILIAL = '0805' THEN '02.082.394/0014-14'
		WHEN F.RA_FILIAL = '0806' THEN '02.082.394/0015-03'
		WHEN F.RA_FILIAL = '0807' THEN '02.082.394/0016-86'
		WHEN F.RA_FILIAL = '0901' THEN '02.359.156/0001-99'
		WHEN F.RA_FILIAL = '1001' THEN '02.397.156/0001-83'
		WHEN F.RA_FILIAL = '1101' THEN '02.987.159/0001-56'
		WHEN F.RA_FILIAL = '1201' THEN '22.434.149/0001-11'
		WHEN F.RA_FILIAL = '1301' THEN '02.082.394/0001-08'
		WHEN F.RA_FILIAL = '1402' THEN '00.866.577/0021-24'
	END AS Empresa_CNPJ,
	CASE
		WHEN F.RA_FILIAL = '0101' THEN 'CTRQ'
		WHEN F.RA_FILIAL = '0102' THEN 'CIA THERMAS DO RIO QUENTE - CALDAS NOVAS'
		WHEN F.RA_FILIAL = '0103' THEN 'CIA THERMAS DO RIO QUENTE - GYN'
		WHEN F.RA_FILIAL = '0104' THEN 'CIA THERMAS DO RIO QUENTE - PATIO BRASIL'
		WHEN F.RA_FILIAL = '0105' THEN 'CIA THERMAS DO RIO QUENTE - STO ANDRE'
		WHEN F.RA_FILIAL = '0106' THEN 'CIA THERMAS DO RIO QUENTE - VALETUR MART'
		WHEN F.RA_FILIAL = '0107' THEN 'FILIAL - MARULHOS'
		WHEN F.RA_FILIAL = '0108' THEN 'POUSADA BRASILIA'
		WHEN F.RA_FILIAL = '0109' THEN 'CIA THERMAS DO RIO QUENTE - SAO CAETANO'
		WHEN F.RA_FILIAL = '0110' THEN 'CIA THERMAS DO RIO QUENTE - VILA LEOPONDIN'
		WHEN F.RA_FILIAL = '0111' THEN 'CIA THERMAS DO RIO QUENTE - IBIRAPUERA'
		WHEN F.RA_FILIAL = '0112' THEN 'CIA THERMAS DO RIO QUENTE - CAMPINAS'
		WHEN F.RA_FILIAL = '0113' THEN 'CIA THERMAS DO RIO QUENTE'
		WHEN F.RA_FILIAL = '0114' THEN 'RIO QUENTE RESORTS - RIBEIRAO PRETO'
		WHEN F.RA_FILIAL = '0201' THEN 'RQSF I'
		WHEN F.RA_FILIAL = '0301' THEN 'RQSF II'
		WHEN F.RA_FILIAL = '0401' THEN 'GIARDINO SUITES'
		WHEN F.RA_FILIAL = '0501' THEN 'ESTANCIA THERMAS POUSADA DO RIO QUENTE'
		WHEN F.RA_FILIAL = '0601' THEN 'ESTANCIA THERMAS DO RIO QUENTE'
		WHEN F.RA_FILIAL = '0701' THEN 'RIO QUENTE EMPREENDIMENTOS E PARTICIPACOE'
		WHEN F.RA_FILIAL = '0801' THEN 'VALE DO RIO QUENTE AG DE VIAGENS E TURIS'
		WHEN F.RA_FILIAL = '0802' THEN 'VALETUR BRASILIA'
		WHEN F.RA_FILIAL = '0803' THEN 'VALE DO RIO QUENTE AG DE VIAGENS E TURIS'
		WHEN F.RA_FILIAL = '0804' THEN 'VALETUR SAO CAETANO'
		WHEN F.RA_FILIAL = '0805' THEN 'VALETUR CALDAS NOVAS'
		WHEN F.RA_FILIAL = '0806' THEN 'VALE DO RIO QUENTE AG DE VIAGENS E TURIS'
		WHEN F.RA_FILIAL = '0807' THEN 'VALE DO RIO QUENTE AG DE VIAGENS E TURIS'
		WHEN F.RA_FILIAL = '0901' THEN 'RIO QUENTE MINERACAO'
		WHEN F.RA_FILIAL = '1001' THEN 'RIO QUENTE EMPREENDIMENTOS IMOBILIARIOS'
		WHEN F.RA_FILIAL = '1101' THEN 'RIO QUENTE INCORPORACOES E VENDAS LTDA'
		WHEN F.RA_FILIAL = '1201' THEN 'VALE DO RIO QUENTE OPERADORA DE TURISMO'
		WHEN F.RA_FILIAL = '1301' THEN 'VALETUR MATRIZ'
		WHEN F.RA_FILIAL = '1402' THEN 'SAUIPE GOIAS'
	END AS Setor,
	CASE
		WHEN C.Q3_DESCSUM IS NULL THEN 'Nao Informado'
		ELSE C.Q3_DESCSUM
	END AS Cargo,
	NULL AS Descricao_Atividades,
	NULL AS Informacoes_Complementares,
	F.RA_MAT AS Matricula,
	F.RA_NOMECMP AS Nome,
	Substr(F.RA_NASC, 7, 2)|| '/' || Substr(F.RA_NASC, 5, 2)|| '/' || Substr(F.RA_NASC, 0, 4) AS Data_Nascimento,
	CASE
		WHEN F.RA_SEXO = 'M' THEN 'Masculino'
		WHEN F.RA_SEXO = 'F' THEN 'Feminino'
	END AS Sexo,
	TO_DATE(Substr(F.RA_ADMISSA, 7, 2)|| '/' || Substr(F.RA_ADMISSA, 5, 2)|| '/' || Substr(F.RA_ADMISSA, 0, 4), 'DD/MM/YYYY') AS Data_Admissao,
	CASE
		WHEN F.RA_ESTCIVI = 'C' THEN 'Casado(a)'
		WHEN F.RA_ESTCIVI = 'D' THEN 'Divorciado(a)'
		WHEN F.RA_ESTCIVI = 'M' THEN 'MARITAL - DECLARACAO DE UNIAO ESTÁVEL'
		WHEN F.RA_ESTCIVI = 'Q' THEN 'Separado(a)'
		WHEN F.RA_ESTCIVI = 'S' THEN 'Solteiro(a)'
		WHEN F.RA_ESTCIVI = 'V' THEN 'Viúvo(a)'
	END AS Estado_Civil,
	F.RA_PIS AS NIT_PIS_PASEP,
	CASE
		WHEN F.RA_RG IN ' ' THEN 'ND'
		ELSE F.RA_RG
	END AS RG,
	REGEXP_REPLACE(LPAD(F.RA_CIC, 11), '([0-9]{3})([0-9]{3})([0-9]{3})', '\1.\2.\3-') AS CPF,
	CASE
		WHEN F.RA_NUMCP IN ' ' THEN 'NULL'
		ELSE F.RA_NUMCP
	END AS CTPS,
	F.RA_SERCP AS SERIE,
	--CASE 
         --WHEN SUBSTR(F.RA_SERCP, 3, 3) IN ' ' THEN 'NULL'
         --ELSE SUBSTR(F.RA_SERCP, 3, 3)
	  --END AS Serie_CTPS,
      NULL AS CNS,      
      CASE 
            WHEN C.Q3_DESCSUM IN 'ESTAGIARIO' AND  F.RA_PIS = ' ' THEN 'ESTAGIARIO'
            WHEN C.Q3_DESCSUM IS NULL AND  F.RA_PIS = ' ' THEN 'ESTAGIARIO'
            WHEN F.RA_TIPOADM = '1A' THEN 'DIRETOR'
            WHEN F.RA_TIPOADM = '1B' THEN 'DIRETOR'
            WHEN F.RA_TIPOADM = '1C' THEN 'DIRETOR'
            WHEN F.RA_TIPOADM = '2A' THEN 'CLT'
            WHEN F.RA_TIPOADM = '2B' THEN 'CLT'
            WHEN F.RA_TIPOADM = '2C' THEN 'CLT'
            WHEN F.RA_TIPOADM = '3A' THEN 'CLT'
            WHEN F.RA_TIPOADM = '3B' THEN 'CLT'
            WHEN F.RA_TIPOADM = '3C' THEN 'CLT'
            WHEN F.RA_TIPOADM = '4B' THEN 'CLT'
            WHEN F.RA_TIPOADM = '51' THEN 'CLT'
            WHEN F.RA_TIPOADM = '52' THEN 'CLT'
            WHEN F.RA_TIPOADM = '53' THEN 'CLT'
            WHEN F.RA_TIPOADM = '54' THEN 'CLT'
            WHEN F.RA_TIPOADM = '55' THEN 'CLT'
            WHEN F.RA_TIPOADM = '56' THEN 'CLT'
            WHEN F.RA_TIPOADM = '9A' THEN 'CLT'
            WHEN F.RA_TIPOADM = '9B' THEN 'CLT'
            WHEN F.RA_TIPOADM = '9C' THEN 'CLT'            
      END AS Vinculo,      
      NULL AS Vinculo_Outro,
      F.RA_LOGRDSC AS Endereco,
      F.RA_LOGRNUM AS Endereco_Numero,
      F.RA_COMPLEM AS Complemento,
      F.RA_MUNICIP AS Cidade,
      F.RA_ESTADO AS Estado,
      F.RA_BAIRRO AS Bairro,
      F.RA_CEP AS CEP,
      F.RA_TELEFON AS Telefone,
      F.RA_NUMCELU AS Celular,
      F.RA_EMAIL AS Email,
      NULL AS Salario,
      NULL AS Jornada_Trabalho,
      CC.CTT_DESC01 AS Centro_Custo,
      NULL AS Codigo_Polo,
      NULL AS Nome_Polo,
      NULL AS CNPJ_Lotacao,
      NULL AS Codigo_Lotacao,
      NULL AS Nome_Lotacao,
      NULL AS Endereco_Lotacao,
      NULL AS Endereco_Lotacao_Numero,
      NULL AS Endereco_Lotacao_Complemento,
      NULL AS Lotacao_Bairro,
      NULL AS Lotacao_CEP,
      NULL AS Cidade_Lotacao,
      NULL AS Estado_Lotacao,    
      CASE 
            WHEN F.RA_SITFOLH = ' ' THEN 'Ativo'
            WHEN F.RA_SITFOLH = 'F' THEN 'Férias'
            WHEN F.RA_SITFOLH = 'T' THEN 'Transferido'
            WHEN F.RA_SITFOLH = 'D' THEN 'Demitido'
            WHEN F.RA_SITFOLH = 'A' THEN 'Afastado' 
      END AS Situacao,      
      NULL AS Situacao_Outro,
      CASE 
            WHEN F.RA_SITFOLH = ' ' THEN NULL
            WHEN (F.RA_SITFOLH = 'F' OR
                 F.RA_SITFOLH = 'T' OR
                 F.RA_SITFOLH = 'A') AND d.r8_dataini IS NOT null 
      THEN Substr(D.R8_DATAINI,7,2)||'/'||Substr(D.R8_DATAINI,5,2)||'/'||Substr(D.R8_DATAINI,0,4) 
      ELSE NULL
      END AS Situacao_Data_Inicio,
      CASE 
            WHEN F.RA_SITFOLH = ' ' THEN NULL
            WHEN (F.RA_SITFOLH = 'F' OR
                  F.RA_SITFOLH = 'T' OR
                  F.RA_SITFOLH = 'A') AND d.r8_datafim <>'        ' AND d.R8_DATA IS NOT NULL THEN Substr(D.R8_DATAFIM,7,2)||'/'||Substr(D.R8_DATAFIM,5,2)||'/'||Substr(D.R8_DATAFIM,0,4)
      		WHEN (F.RA_SITFOLH = 'F' OR
                  F.RA_SITFOLH = 'T' OR
                  F.RA_SITFOLH = 'A') AND D.R8_DATAFIM='        ' THEN '01/01/9999'
            WHEN F.RA_SITFOLH = 'D' THEN to_char(TO_DATE(F.RA_DEMISSA,'YYYYMMDD'),'dd/mm/yyyy')
      END AS Situacao_Data_Fim, 
		 --CASE
			  --WHEN F.RA_SITFOLH = 'D' AND F.RA_SITFOLH = 'F' AND F.RA_SITFOLH = 'A' THEN Substr(D.R8_DATAFIM,7,2)||'/'||Substr(D.R8_DATAFIM,5,2)||'/'||Substr(D.R8_DATAFIM,0,4)
			  --WHEN F.RA_SITFOLH IN (' ','F','T','A') THEN '31/12/9999'
		 --END AS Situacao_Data_Fim, 
      CASE 
          WHEN F.RA_MAE IN ' ' THEN 'Nao Informado'
          ELSE F.RA_MAE 
      END AS Nome_Mae,
      NULL AS Contato_Emergencia,
      CASE 
      	WHEN F.RA_TPDEFFI=' ' THEN NULL
      	WHEN F.RA_TPDEFFI='6' THEN 'Reabilitado'
      	WHEN F.RA_TPDEFFI<>'6'AND F.RA_TPDEFFI<>'0' THEN 'PCD'
      	END AS Deficiencia,
      CASE
      	WHEN F.RA_TPDEFFI='1' THEN 'Físico'
      	WHEN F.RA_TPDEFFI='2' THEN 'Auditivo'
      	WHEN F.RA_TPDEFFI='3' THEN 'Visual'
      	WHEN F.RA_TPDEFFI='4' THEN 'Mental'
      	WHEN F.RA_TPDEFFI='5' THEN 'Múltipla'
      	WHEN F.RA_TPDEFFI='6' THEN 'Reabilitação Profissional'
      	END AS Deficiencia_Classificacao, 
      NULL AS Estabilidade,
      NULL AS Estabilidade_Data_Inicio,
      NULL AS Estabilidade_Data_Fim,
      NULL AS Riscos,
      NULL AS Risco_Outros,   
      NULL AS Hierarquia,
      NULL AS Nacionalidade,
      NULL AS Nome_Dependentes,
      NULL AS Grau_Parentesco_Dependentes, 
      NULL AS Sexo_Dependentes,
      NULL AS Dt_Nascimento_Dependentes,
      NULL AS Prestador,
      NULL AS Negocio,
      NULL AS Diretoria,
      NULL AS Gerencia,
      NULL AS AssitenciaMedica,
      NULL AS Arredondamento,
      NULL AS DevolucaoPagamentoMaior, 
      NULL AS MesalidadeAssistenciaMedica,
      NULL AS Coparticipacao,
      NULL AS AssistenciaOdontologica,
      NULL AS SeguroVida,
      NULL AS FGTS,
      NULL AS ValorAssistenciaMedica,
      F.RA_CODUNIC AS IdEsocial,
      NULL AS CodigoCBO,
      NULL AS Exclusao
FROM SIGA.SRA010 F
      LEFT JOIN SIGA.CTT010 CC ON (F.RA_CC = CC.CTT_CUSTO  AND Substr(F.RA_FILIAL,0,2) = trim(CC.CTT_FILIAL))
      LEFT JOIN SIGA.SQ3010 C  ON (F.RA_CARGO = C.Q3_CARGO AND Substr(F.RA_FILIAL,0,2) = trim(C.Q3_FILIAL))
      LEFT JOIN (SELECT R8_MAT, MAX(R8_SEQ) AS SEQ FROM SIGA.SR8010 GROUP BY R8_MAT) S ON (F.RA_MAT = S.R8_MAT)
      LEFT JOIN SIGA.SR8010 D  ON (S.R8_MAT = D.R8_MAT) AND D.R8_SEQ = S.SEQ AND D.D_E_L_E_T_ = ' '    
WHERE F.D_E_L_E_T_ = ' ' AND F.RA_MAT NOT LIKE 'T%' AND F.RA_MAT NOT LIKE 'R%' AND F.RA_MAT <>' ' AND
	 (F.RA_SITFOLH IN (' ','A','F','T') OR 
	 (F.RA_SITFOLH='D' AND CASE WHEN F.RA_DEMISSA<>' ' 
AND f.ra_demissa IS NOT NULL THEN TO_DATE(F.RA_DEMISSA,'YYYYMMDD') end >TO_DATE('20190701','YYYYMMDD')))