SELECT IDEMPRESA, IDDOCUMENTO, IDMODELO, FLGTIPO, DATAMOVIMENTO, NUMDOCUMENTOINI, FLGAMBIENTENFE FROM LFDOCUMENTOFISCAL WHERE DATAMOVIMENTO >= '01/07/2014'   AND  FLGAMBIENTENFE ='2' AND idmodelo = '27';

UPDATE LFDOCUMENTOFISCAL
  SET FLGAMBIENTENFE   ='1'
    WHERE DATAMOVIMENTO >='01/07/2014' AND
          IDMODELO='27' AND
          FLGAMBIENTENFE ='2' AND
          IDEMPRESA ='1'
